default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: blog_development 

test:
  <<: *default
  database: aws_rails_test

production:
  <<: *default
  database: aws_rails_production
  username: deploy
  password: Myaws@12
